(() => {
  'use strict';
  const canvas = document.querySelector('#game'), ctx = canvas.getContext('2d');
  const $ = (id) => document.getElementById(id);
  const ui = { level:$('level'), xpFill:$('xpFill'), xpText:$('xpText'), timer:$('timer'), wave:$('waveLabel'), kills:$('kills'), hpText:$('hpText'), hpFill:$('hpFill'), start:$('startScreen'), upgrade:$('upgradeScreen'), pause:$('pauseScreen'), over:$('gameOverScreen'), hint:$('hint'), boss:$('bossHud'), bossFill:$('bossHpFill'), bossText:$('bossHpText'), toast:$('bossToast') };
  const keys = new Set();
  const rand = (a,b) => a + Math.random()*(b-a);
  const clamp = (v,a,b) => Math.max(a,Math.min(b,v));
  const upgrades = [
    {id:'damage',icon:'✹',name:'과충전 코일',tag:'공격력',desc:'공격력 +35%',apply:s=>s.damage*=1.35},
    {id:'speed',icon:'➤',name:'질주 프로토콜',tag:'이동',desc:'이동 속도 +18%',apply:s=>s.speed*=1.18},
    {id:'rate',icon:'⌁',name:'연사 회로',tag:'공격 속도',desc:'공격 속도 +22%',apply:s=>s.fireRate=Math.max(.19,s.fireRate*.78)},
    {id:'heal',icon:'✚',name:'응급 나노봇',tag:'회복',desc:'체력 +35',apply:s=>{s.maxHp+=35;s.hp=Math.min(s.maxHp,s.hp+35)}},
    {id:'magnet',icon:'◉',name:'자기장 증폭',tag:'잔광',desc:'잔광 흡수 범위 +55%',apply:s=>s.magnet*=1.55},
    {id:'pierce',icon:'⟿',name:'관통 탄자',tag:'관통',desc:'관통 +1',apply:s=>s.pierce++},
    {id:'orbit',icon:'⟳',name:'보호 위성',tag:'위성',desc:'위성 +1 · 접촉 피해',apply:s=>s.orbit++},
    {id:'heart',icon:'♥',name:'강화 외골격',tag:'체력',desc:'최대 체력 +25, 회복 +25',apply:s=>{s.maxHp+=25;s.hp=Math.min(s.maxHp,s.hp+25)}},
  ];
  const MAX_LEVEL=1+upgrades.length, RECORD_KEY='afterglow_records_v1';
  const state = {running:false,paused:false,ended:false,time:0,last:0,spawn:0,fire:0,orbitClock:0,nextBoss:60,bossesDefeated:0,pendingEvolutions:0,evolution:null,pickedUpgrades:[],level:1,xp:0,xpNeed:12,kills:0,shake:0,flash:0,player:null,enemies:[],shots:[],gems:[],particles:[],orbit:0,damage:22,fireRate:.64,speed:205,magnet:92,pierce:0,keys,world:{x:0,y:0},sound:true,touchX:0,touchY:0};
  let W=1,H=1,dpr=1,audio;
  function resize(){const r=canvas.getBoundingClientRect();dpr=Math.min(devicePixelRatio||1,2);W=r.width;H=r.height;canvas.width=Math.round(W*dpr);canvas.height=Math.round(H*dpr);ctx.setTransform(dpr,0,0,dpr,0,0)}
  new ResizeObserver(resize).observe(canvas); resize();
  function beep(freq=440,duration=.06,type='sine',volume=.035){if(!state.sound)return;try{audio ||= new (window.AudioContext||window.webkitAudioContext)();if(audio.state==='suspended')audio.resume();const o=audio.createOscillator(),g=audio.createGain();o.type=type;o.frequency.value=freq;g.gain.setValueAtTime(volume,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+duration);o.connect(g);g.connect(audio.destination);o.start();o.stop(audio.currentTime+duration)}catch{}}
  function reset(){Object.assign(state,{running:true,paused:false,ended:false,time:0,last:performance.now(),spawn:0,fire:0,orbitClock:0,nextBoss:60,bossesDefeated:0,pendingEvolutions:0,evolution:null,pickedUpgrades:[],level:1,xp:0,xpNeed:12,kills:0,shake:0,flash:0,damage:22,fireRate:.64,speed:205,magnet:92,pierce:0,orbit:0,enemies:[],shots:[],gems:[],particles:[],touchX:0,touchY:0,player:{x:0,y:0,r:13,hp:100,maxHp:100,invuln:0,facing:1}});keys.clear();$('stickNub').style.transform='translate(0,0)';ui.boss.classList.add('hidden');ui.toast.classList.add('hidden');hideAll();ui.hint.style.opacity='1';updateHud()}
  function hideAll(){ui.start.classList.add('hidden');ui.upgrade.classList.add('hidden');ui.pause.classList.add('hidden');ui.over.classList.add('hidden')}
  function start(){reset();beep(520,.12,'triangle')}
  function pause(){if(!state.running||state.ended||!ui.upgrade.classList.contains('hidden'))return;state.paused=!state.paused;ui.pause.classList.toggle('hidden',!state.paused);if(!state.paused)state.last=performance.now()}
  function readRecords(){try{const value=JSON.parse(localStorage.getItem(RECORD_KEY)||'{}');return{survival:Number.isFinite(value.survival)?Math.max(0,value.survival):0,bosses:Number.isFinite(value.bosses)?Math.max(0,value.bosses):0}}catch{return{survival:0,bosses:0}}}
  function end(){state.running=false;state.ended=true;ui.over.classList.remove('hidden');$('finalTime').textContent=formatTime(state.time);$('finalKills').textContent=state.kills;$('finalLevel').textContent=state.level;const won=state.time>=300,previous=readRecords(),survival=Math.max(previous.survival,Math.floor(state.time)),bosses=Math.max(previous.bosses,state.bossesDefeated),record=survival>previous.survival||bosses>previous.bosses;try{localStorage.setItem(RECORD_KEY,JSON.stringify({survival,bosses}))}catch{}$('recordBadge').classList.toggle('hidden',!record);$('recordLine').textContent=`최고 ${formatTime(survival)} · 보스 ${bosses}`;$('resultTitle').textContent=won?'생존 성공':'생존 실패';$('resultCopy').textContent=won?'새벽을 지켜냈다.':'다시 출격하라.';$('resultMark').textContent=won?'☼':'✦';beep(won?680:110,.5,won?'sine':'sawtooth',.07)}
  function formatTime(t){const m=Math.floor(t/60),s=Math.floor(t%60);return `${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`}
  function updateHud(){ui.level.textContent=state.level;ui.xpText.textContent=state.level>=MAX_LEVEL?'MAX':`${Math.floor(state.xp)} / ${state.xpNeed}`;ui.xpFill.style.width=state.level>=MAX_LEVEL?'100%':`${Math.min(100,state.xp/state.xpNeed*100)}%`;ui.timer.textContent=formatTime(state.time);ui.kills.textContent=state.kills;const p=state.player;if(p){const ratio=p.hp/p.maxHp;ui.hpText.textContent=`${Math.ceil(ratio*100)}%`;ui.hpFill.style.width=`${100*ratio}%`;ui.hpFill.style.background=ratio<.3?'#ff667a':''}const boss=state.enemies.find(e=>e.kind==='boss'&&!e.dead);ui.boss.classList.toggle('hidden',!boss);if(boss){ui.bossFill.style.width=`${Math.max(0,boss.hp/boss.maxHp*100)}%`;ui.bossText.textContent=`${Math.ceil(boss.hp/boss.maxHp*100)}%`;$('bossName').textContent=boss.name}const stage=['고요','추격','혼란','최후','새벽'][Math.min(4,Math.floor(state.time/60))];ui.wave.textContent=boss?`보스 · ${boss.name}`:`${Math.min(5,Math.floor(state.time/60)+1)}분 · ${stage}`}
  function spawnEnemy(){const angle=rand(0,Math.PI*2),dist=Math.max(W,H)*.62+rand(15,130),x=state.player.x+Math.cos(angle)*dist,y=state.player.y+Math.sin(angle)*dist,t=state.time;let e={x,y,r:12,hp:34,maxHp:34,speed:rand(39,52)+Math.min(12,t*.04),dmg:10,color:'#ff807e',kind:'drifter',xp:1};if(t>18&&Math.random()<Math.min(.52,.16+t/260)){e={x,y,r:18,hp:105,maxHp:105,speed:rand(25,33)+Math.min(10,t*.02),dmg:19,color:'#bd91ff',kind:'brute',xp:3}}if(t>38&&Math.random()<.17){e={x,y,r:9,hp:21,maxHp:21,speed:rand(67,78)+Math.min(8,t*.015),dmg:8,color:'#ffd17a',kind:'wisp',xp:1}}state.enemies.push(e)}
  function burst(x,y,color,n=5){for(let i=0;i<n;i++){const a=rand(0,Math.PI*2),v=rand(30,150);state.particles.push({x,y,vx:Math.cos(a)*v,vy:Math.sin(a)*v,life:rand(.18,.5),max:.5,r:rand(1,3),color})}}
  function damageEnemy(e,n){if(e.dead)return;e.hp-=n;if(e.hp<=0){e.dead=true;state.kills++;burst(e.x,e.y,e.color,e.kind==='boss'?26:e.kind==='brute'?11:6);if(e.kind==='boss'){state.bossesDefeated++;state.gems.push({x:e.x,y:e.y,r:11,value:8,phase:rand(0,7),color:'#ffe69a',core:true});state.shake=13;beep(180,.42,'triangle',.075)}else state.gems.push({x:e.x,y:e.y,r:e.xp>1?7:5,value:e.xp,phase:rand(0,7),color:e.xp>1?'#c9a0ff':'#79efd0'});if(e.kind==='brute')state.shake=5}}
  function spawnBoss(){const p=state.player,index=state.bossesDefeated,angle=rand(0,Math.PI*2),dist=Math.max(W,H)*.62+100,names=['워든','공허왕','야간 엔진'];const hp=400+index*240;const e={x:p.x+Math.cos(angle)*dist,y:p.y+Math.sin(angle)*dist,r:29+Math.min(8,index*2),hp,maxHp:hp,speed:27+index*3,dmg:18+index*2,color:'#c48aff',kind:'boss',xp:0,name:names[Math.min(index,names.length-1)],attackTimer:2.2,windup:0,charge:0,dashX:0,dashY:0};state.enemies.push(e);ui.toast.textContent=`보스 출현 · ${e.name}`;ui.toast.classList.remove('hidden');ui.toast.classList.add('show');setTimeout(()=>{ui.toast.classList.remove('show');ui.toast.classList.add('hidden')},2400);beep(145,.55,'sawtooth',.045)}
  function getTarget(){let nearest=null,best=520**2,boss=state.enemies.find(e=>e.kind==='boss'&&!e.dead);if(boss){const d=(boss.x-state.player.x)**2+(boss.y-state.player.y)**2;if(d<650**2)return boss}for(const e of state.enemies){if(e.dead)continue;const d=(e.x-state.player.x)**2+(e.y-state.player.y)**2;if(d<best){best=d;nearest=e}}return nearest}
  function showChoices(options,{eyebrow,title,subtitle,note,onPick}){state.paused=true;$('upgradeEyebrow').textContent=eyebrow;$('upgradeTitle').textContent=title;$('upgradeSubtitle').textContent=subtitle;$('upgradeNote').textContent=note;$('upgradeList').innerHTML='';for(const u of options){const b=document.createElement('button');b.className='upgrade-card';b.innerHTML=`<span class="upgrade-icon">${u.icon}</span><span class="upgrade-tag">${u.tag}</span><h3>${u.name}</h3><p>${u.desc}</p>`;b.addEventListener('click',()=>{onPick(u);ui.upgrade.classList.add('hidden');state.paused=false;state.last=performance.now();beep(750,.13,'triangle');updateHud()},{once:true});$('upgradeList').append(b)}ui.upgrade.classList.remove('hidden')}
  function levelUp(){state.level++;state.xp-=state.xpNeed;state.xpNeed=Math.round(state.xpNeed*1.27+5);const options=upgrades.filter(u=>!state.pickedUpgrades.includes(u.id)).sort(()=>Math.random()-.5).slice(0,3);if(!options.length)return;showChoices(options,{eyebrow:'강화',title:'강화 선택',subtitle:'하나를 골라라',note:'선택 후 계속',onPick:u=>{state.pickedUpgrades.push(u.id);u.apply(state)}});beep(820,.2,'sine',.06)}
  function chooseEvolution(){if(!state.pendingEvolutions||state.evolution)return;const options=[
    {id:'flare',icon:'✺',name:'태양 폭발',tag:'EVOLUTION',desc:'탄환이 적중하면 주변까지 폭발 피해를 줍니다.'},
    {id:'echo',icon:'⋙',name:'잔상 연사',tag:'EVOLUTION',desc:'한 번 발사할 때 부채꼴로 탄환 세 발을 쏩니다.'},
    {id:'lance',icon:'⟿',name:'새벽의 창',tag:'EVOLUTION',desc:'탄환 피해가 30% 증가하고 모든 적을 관통합니다.'}
  ];showChoices(options,{eyebrow:'보스 코어',title:'무기 진화',subtitle:'하나를 골라라',note:'진화는 이번 판 유지',onPick:u=>{state.evolution=u.id;state.pendingEvolutions--;if(u.id==='lance'){state.damage*=1.3;state.pierce=99}}});beep(960,.24,'sine',.07)}
  function processRewards(){if(state.paused||state.ended)return;if(state.level<MAX_LEVEL&&state.xp>=state.xpNeed){levelUp();return}if(state.pendingEvolutions&&!state.evolution)chooseEvolution()}
  function update(dt){const p=state.player;state.time+=dt;state.spawn-=dt;state.fire-=dt;p.invuln=Math.max(0,p.invuln-dt);if(state.flash>0)state.flash-=dt;state.shake=Math.max(0,state.shake-dt*18);
    const k=keys;let mx=(k.has('d')||k.has('arrowright')?1:0)-(k.has('a')||k.has('arrowleft')?1:0)+state.touchX,my=(k.has('s')||k.has('arrowdown')?1:0)-(k.has('w')||k.has('arrowup')?1:0)+state.touchY;if(mx||my){const l=Math.max(1,Math.hypot(mx,my));mx/=l;my/=l;p.x+=mx*state.speed*dt;p.y+=my*state.speed*dt;if(Math.abs(mx)>.1)p.facing=Math.sign(mx)}
    // The five-minute endpoint doubles enemy movement speed. A 0.72s spawn
    // floor and 45-enemy cap keep late pressure tense but readable.
    const difficulty=1+state.time/300;const spawnInterval=Math.max(.72,1.08-state.time/700);if(state.time>=state.nextBoss&&state.nextBoss<300){spawnBoss();state.nextBoss+=90}if(state.spawn<=0){if(state.enemies.length<45){spawnEnemy();state.spawn=Math.max(.72,spawnInterval*(Math.random()<Math.min(.3,state.time/400)? .78:1))}else state.spawn=.2}
    if(state.fire<=0){const e=getTarget();if(e){const base=Math.atan2(e.y-p.y,e.x-p.x),angles=state.evolution==='echo'?[base-.2,base,base+.2]:[base];for(const a of angles)state.shots.push({x:p.x+Math.cos(a)*14,y:p.y+Math.sin(a)*14,vx:Math.cos(a)*570,vy:Math.sin(a)*570,r:state.evolution==='lance'?5:4,life:1.15,damage:state.damage*(state.evolution==='echo'?.64:1),pierce:state.pierce,hit:new Set(),splash:state.evolution==='flare'?72:0});state.fire=state.fireRate;beep(300+Math.random()*90,.035,'triangle',.012)}}
    for(const e of state.enemies){if(e.dead)continue;let dx=p.x-e.x,dy=p.y-e.y,d=Math.hypot(dx,dy)||1;if(e.kind==='boss'){if(e.windup>0){e.windup-=dt;if(e.windup<=0)e.charge=.38}else if(e.charge>0)e.charge=Math.max(0,e.charge-dt);else{e.attackTimer-=dt;if(e.attackTimer<=0){e.windup=.72;e.attackTimer=2.5;dx=p.x-e.x;dy=p.y-e.y;d=Math.hypot(dx,dy)||1;e.dashX=dx/d;e.dashY=dy/d}}if(e.charge>0){e.x+=e.dashX*e.speed*4*difficulty*dt;e.y+=e.dashY*e.speed*4*difficulty*dt}else{const rush=e.windup>0?.42:1;e.x+=dx/d*e.speed*difficulty*rush*dt;e.y+=dy/d*e.speed*difficulty*rush*dt}}else{e.x+=dx/d*e.speed*difficulty*dt;e.y+=dy/d*e.speed*difficulty*dt}if(d<e.r+p.r&&p.invuln<=0){p.hp-=e.dmg;p.invuln=.58;state.shake=8;state.flash=.2;burst(p.x,p.y,'#ff9b87',9);beep(95,.15,'sawtooth',.055);if(p.hp<=0){p.hp=0;updateHud();end();return}}}
    if(state.orbit){state.orbitClock+=dt;if(state.orbitClock>=.22){state.orbitClock%=.22;for(let i=0;i<state.orbit;i++){const a=state.time*2.7+i*Math.PI*2/state.orbit,ox=p.x+Math.cos(a)*42,oy=p.y+Math.sin(a)*42;for(const e of state.enemies){if(!e.dead&&Math.hypot(e.x-ox,e.y-oy)<e.r+6)damageEnemy(e,12)}}}}
    for(const s of state.shots){s.x+=s.vx*dt;s.y+=s.vy*dt;s.life-=dt;for(const e of state.enemies){if(e.dead||s.hit.has(e))continue;if(Math.hypot(e.x-s.x,e.y-s.y)<e.r+s.r){s.hit.add(e);damageEnemy(e,s.damage);if(s.splash&&!s.splashDone){s.splashDone=true;burst(s.x,s.y,'#ffd58e',12);for(const other of state.enemies)if(other!==e&&!other.dead&&Math.hypot(other.x-s.x,other.y-s.y)<s.splash)damageEnemy(other,s.damage*.58)}s.pierce--;if(s.pierce<0){s.life=0;break}}}}state.shots=state.shots.filter(s=>s.life>0);
    for(const g of state.gems){g.phase+=dt*3;const dx=p.x-g.x,dy=p.y-g.y,d=Math.hypot(dx,dy)||1;if(d<state.magnet||g.core&&d<state.magnet*1.7){const pull=(g.core?155:100)+Math.max(0,state.magnet-d)*5;g.x+=dx/d*pull*dt;g.y+=dy/d*pull*dt}if(d<p.r+g.r+5){g.got=true;state.xp+=g.core?(state.evolution?16:8):g.value;if(g.core&&!state.evolution)state.pendingEvolutions++;burst(g.x,g.y,g.color,g.core?16:3);beep(g.core?980:580+Math.random()*250,.08,'sine',.04)}}state.gems=state.gems.filter(g=>!g.got);
    for(const q of state.particles){q.x+=q.vx*dt;q.y+=q.vy*dt;q.vx*=.95;q.vy*=.95;q.life-=dt}state.particles=state.particles.filter(q=>q.life>0);state.enemies=state.enemies.filter(e=>!e.dead);if(state.time>=300){end();return}processRewards();updateHud();
  }
  function draw(){ctx.clearRect(0,0,W,H);const p=state.player;if(!p){drawBackdrop(0,0);return}const cx=W/2,cy=H/2,camx=p.x,camy=p.y,now=performance.now()/1000;ctx.save();if(state.shake)ctx.translate(rand(-state.shake,state.shake),rand(-state.shake,state.shake));drawBackdrop(camx,camy);ctx.save();ctx.translate(cx-camx,cy-camy);
    for(const g of state.gems){const pulse=1+Math.sin(g.phase)*.15;ctx.save();ctx.translate(g.x,g.y);ctx.rotate(Math.PI/4);ctx.fillStyle=g.color;ctx.shadowBlur=14;ctx.shadowColor=g.color;ctx.fillRect(-g.r*pulse/2,-g.r*pulse/2,g.r*pulse,g.r*pulse);ctx.restore()}
    for(const e of state.enemies){if(e.kind==='boss'&&e.windup>0){ctx.save();ctx.setLineDash([7,8]);ctx.strokeStyle=`rgba(255,190,249,${.3+.35*Math.sin(now*20)})`;ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(e.x,e.y);ctx.lineTo(e.x+e.dashX*260,e.y+e.dashY*260);ctx.stroke();ctx.setLineDash([]);ctx.restore()}ctx.save();ctx.translate(e.x,e.y);const pulse=1+Math.sin(now*5+e.y)*.06;ctx.scale(pulse,pulse);ctx.fillStyle=e.color+'24';ctx.beginPath();ctx.arc(0,0,e.r*1.6,0,Math.PI*2);ctx.fill();ctx.fillStyle=e.color;ctx.shadowBlur=e.kind==='boss'?32:e.kind==='brute'?22:13;ctx.shadowColor=e.color;ctx.beginPath();if(e.kind==='wisp'){ctx.moveTo(0,-e.r);ctx.lineTo(e.r*.72,0);ctx.lineTo(0,e.r);ctx.lineTo(-e.r*.72,0)}else ctx.arc(0,0,e.r,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;if(e.kind!=='boss'){ctx.fillStyle='#101421';ctx.beginPath();ctx.arc(-e.r*.27,-e.r*.1,2,0,7);ctx.arc(e.r*.27,-e.r*.1,2,0,7);ctx.fill()}if(e.kind==='boss'||e.hp<e.maxHp){ctx.fillStyle='#ffffff2a';ctx.fillRect(-e.r,-e.r-8,e.r*2,3);ctx.fillStyle=e.kind==='boss'?'#e6b5ff':e.color;ctx.fillRect(-e.r,-e.r-8,e.r*2*Math.max(0,e.hp/e.maxHp),3)}ctx.restore()}
    for(const s of state.shots){ctx.fillStyle=s.splash?'#ffd58e':state.evolution==='lance'?'#f0d2ff':'#c8fff0';ctx.shadowBlur=12;ctx.shadowColor=s.splash?'#ffd58e':'#8effd9';ctx.beginPath();ctx.arc(s.x,s.y,s.r,0,Math.PI*2);ctx.fill()}ctx.shadowBlur=0;
    if(state.orbit){for(let i=0;i<state.orbit;i++){const a=now*2.7+i*Math.PI*2/state.orbit,x=p.x+Math.cos(a)*42,y=p.y+Math.sin(a)*42;ctx.fillStyle='#9ef3df';ctx.shadowBlur=13;ctx.shadowColor='#9ef3df';ctx.beginPath();ctx.arc(x,y,5,0,7);ctx.fill()}ctx.shadowBlur=0;ctx.strokeStyle='#94f5dc22';ctx.beginPath();ctx.arc(p.x,p.y,42,0,Math.PI*2);ctx.stroke()}
    ctx.save();ctx.translate(p.x,p.y);if(p.invuln>0&&Math.floor(now*18)%2)ctx.globalAlpha=.35;ctx.fillStyle='#86f3d2';ctx.shadowBlur=25;ctx.shadowColor='#6ef0c4';ctx.beginPath();ctx.arc(0,0,p.r+6,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;ctx.fillStyle='#17293a';ctx.beginPath();ctx.arc(0,0,p.r,0,Math.PI*2);ctx.fill();ctx.fillStyle='#baffeb';ctx.beginPath();ctx.arc(0,0,p.r-4,0,Math.PI*2);ctx.fill();ctx.fillStyle='#17333b';ctx.beginPath();ctx.arc(p.facing*4,-2,2.5,0,7);ctx.fill();ctx.restore();
    for(const q of state.particles){ctx.globalAlpha=Math.max(0,q.life/q.max);ctx.fillStyle=q.color;ctx.beginPath();ctx.arc(q.x,q.y,q.r,0,7);ctx.fill()}ctx.globalAlpha=1;
    // A subtle beacon emphasizes the player's safe-to-unsafe transition without obscuring enemies.
    const vg=ctx.createRadialGradient(cx,cy,60,cx,cy,Math.max(W,H)*.62);vg.addColorStop(0,'#0b102000');vg.addColorStop(1,'#0508149e');ctx.fillStyle=vg;ctx.fillRect(camx-cx,camy-cy,W,H);ctx.restore();
    if(state.flash>0){ctx.fillStyle=`rgba(255,100,115,${state.flash*.28})`;ctx.fillRect(0,0,W,H)}ctx.restore();
  }
  function drawBackdrop(camx,camy){ctx.fillStyle='#111a2b';ctx.fillRect(0,0,W,H);const step=48,ox=((W/2-camx)%step+step)%step,oy=((H/2-camy)%step+step)%step;ctx.strokeStyle='#a4c3ed0b';ctx.lineWidth=1;ctx.beginPath();for(let x=ox;x<W;x+=step){ctx.moveTo(x,0);ctx.lineTo(x,H)}for(let y=oy;y<H;y+=step){ctx.moveTo(0,y);ctx.lineTo(W,y)}ctx.stroke();const sx=(((W/2-camx)*.22)%240+240)%240,sy=(((H/2-camy)*.22)%240+240)%240;ctx.fillStyle='#85edcb13';for(let x=sx;x<W;x+=240)for(let y=sy;y<H;y+=240){ctx.beginPath();ctx.arc(x,y,1.3,0,7);ctx.fill()}}
  function frame(now){requestAnimationFrame(frame);if(state.running&&!state.paused&&!state.ended){const dt=Math.min(.04,(now-state.last)/1000||0);state.last=now;update(dt)}draw()}
  requestAnimationFrame(frame);
  $('startBtn').addEventListener('click',start);$('restartBtn').addEventListener('click',start);$('pauseBtn').addEventListener('click',pause);$('resumeBtn').addEventListener('click',pause);$('soundBtn').addEventListener('click',()=>{state.sound=!state.sound;$('soundBtn').innerHTML=state.sound?'♫ <span>사운드</span>':'♪̸ <span>음소거</span>';if(state.sound)beep()});
  const stick=$('touchStick'),nub=$('stickNub');let stickPointer=null;function setStick(e){const r=stick.getBoundingClientRect(),dx=e.clientX-(r.left+r.width/2),dy=e.clientY-(r.top+r.height/2),max=r.width*.34,len=Math.hypot(dx,dy),scale=len>max?max/len:1;state.touchX=dx*scale/max;state.touchY=dy*scale/max;nub.style.transform=`translate(${dx*scale}px,${dy*scale}px)`}function releaseStick(){stickPointer=null;state.touchX=0;state.touchY=0;nub.style.transform='translate(0,0)'}stick.addEventListener('pointerdown',e=>{e.preventDefault();stickPointer=e.pointerId;stick.setPointerCapture(e.pointerId);setStick(e)});stick.addEventListener('pointermove',e=>{if(e.pointerId===stickPointer){e.preventDefault();setStick(e)}});stick.addEventListener('pointerup',e=>{if(e.pointerId===stickPointer)releaseStick()});stick.addEventListener('pointercancel',releaseStick);stick.addEventListener('lostpointercapture',releaseStick);
  window.addEventListener('keydown',e=>{const k=e.key.toLowerCase();if(['arrowup','arrowdown','arrowleft','arrowright',' '].includes(k))e.preventDefault();keys.add(k);if(k===' '&&!e.repeat)pause();if(k==='enter'&&!state.running&&!state.ended)start()});window.addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));window.addEventListener('blur',()=>{if(state.running&&!state.paused)pause()});
})();
