(()=>{'use strict';const $=id=>document.getElementById(id),E=CoopEngine,ctx=$('canvas').getContext('2d'),colors=['#ffbc61','#69dbde','#dd96ee','#8ce799','#ff8397','#9eaaff','#eee381','#70b9ef'];let state=null,local=true,paused=false,net,keys={},last=performance.now(),acc=0,publish=0,lastSent='',muted=false,lastStatus='',target=null,connecting=false; if(new URLSearchParams(location.search).get('quiet')==='1'){muted=true;window.CoopAudio?.setMuted(true);$('mute').textContent='♩';$('mute').setAttribute('aria-label','소리 켜기');$('mute').setAttribute('aria-pressed','true');}
const levelCount=E.LEVEL_COUNT||20,chapters=['첫 합류','협동의 기술','엇갈린 작전','모두의 피날레'],progressKey='chamchi-park-progress-v1';let highestClear=-1;try{highestClear=Math.max(-1,Math.min(levelCount-1,Number(localStorage.getItem(progressKey)??-1)||0))}catch{}
const selectedLevel=el=>Math.max(0,Math.min(levelCount-1,Number(el.value)||0));
function stageOptions(el){for(let chapter=0;chapter<Math.ceil(levelCount/5);chapter++){const group=document.createElement('optgroup');group.label=`${chapter+1} · ${chapters[chapter]||'함께 앞으로'}`;for(let n=chapter*5;n<Math.min(levelCount,chapter*5+5);n++){const option=document.createElement('option');option.value=n;option.textContent=`${String(n+1).padStart(2,'0')} · ${E.level(n,2).name}`;group.appendChild(option)}el.appendChild(group)}}
stageOptions($('localStage'));stageOptions($('roomStage'));
function recommendStage(){const next=Math.min(levelCount-1,highestClear+1);$('localStage').value=next;$('local').textContent=highestClear>=0&&highestClear<levelCount-1?'🎮 이어서 둘이':'🎮 둘이 연습';$('campaignProgress').textContent=highestClear<0?`${levelCount} STAGES · 4 CHAPTERS`:`최고 클리어 · ${highestClear+1} / ${levelCount}`}
recommendStage();
const audio=()=>window.CoopAudio;function sound(name){audio()?.play(name)}function message(s){$('message').textContent=s}function focusGame(){keys={};document.activeElement?.blur?.();$('canvas').focus()}function showGame(){const entering=$('game').style.display!=='block';$('title').hidden=true;$('lobby').hidden=true;$('game').style.display='block';if(entering)focusGame();audio()?.startMusic();}
function reset(n){paused=false;keys={};acc=0;publish=0;target=null;focusGame();const ids=local?['local1','local2']:Object.keys(net.room.players||{});state=E.create(ids,n);lastStatus='';$('overlay').style.display='none';if(!local)net.start(state);showGame();}
$('local').onclick=async()=>{local=true;await audio()?.unlock();reset(selectedLevel($('localStage')))};
async function enter(create){if(connecting)return;connecting=true;for(const id of ['create','join','local'])$(id).disabled=true;message('연결 중…');try{audio()?.unlock();local=false;net=new CoopNetwork(room=>{ $('roomCode').textContent=net.code;const ids=Object.keys(room.players||{});$('members').textContent=ids.map((id,i)=>'● '+room.players[id].name+(id===room.host?' ♛':'')).join('   ');$('start').disabled=!net.host||ids.length<2;$('lobbyHint').textContent=ids.length<2?'친구를 기다리는 중':'함께 출발해요';$('roomStage').disabled=!net.host;$('roomStage').value=Math.max(0,Math.min(levelCount-1,Number(room.selectedLevel)||0));if(room.status==='lobby'){state=null;target=null;paused=false;audio()?.stopMusic();$('game').style.display='none';$('overlay').style.display='none';$('title').hidden=true;$('lobby').hidden=false;return;}if(room.state&&room.status!=='lobby'){if(net.host&&room.state.players.map(p=>p.id).sort().join('|')!==ids.slice().sort().join('|')){if(ids.length<2){state=null;target=null;net.ref.update({status:'lobby',state:null}).catch(e=>message(e.message));}else{state=E.create(ids,room.state.level);lastStatus='';net.start(state);}return;}for(const key of ['platforms','switches','crates','hazards'])room.state.map[key]=room.state.map[key]||[];if(net.justBecameHost){state=JSON.parse(JSON.stringify(room.state));net.justBecameHost=false;}if(!net.host){const before=target||state;target=room.state;const restart=!state||state.level!==target.level||state.status!==target.status||state.players.length!==target.players.length||target.ticks<state.ticks;if(restart){state=JSON.parse(JSON.stringify(target));if(target.status==='play'){paused=false;focusGame()}}events(before||target,target);}else if(state&&state.players.some(p=>!room.players[p.id])){state.players=state.players.filter(p=>room.players[p.id]);}showGame();}},message);const code=create?Math.random().toString(36).slice(2,7).toUpperCase():$('code').value.trim().toUpperCase();if(!code)throw Error('방 코드를 입력해주세요');await net.enter(code,create);$('title').hidden=true;$('lobby').hidden=false;message('');sound('join');}catch(e){local=true;message(e.message)}finally{connecting=false;for(const id of ['create','join','local'])$(id).disabled=false}}
$('create').onclick=()=>enter(true);$('join').onclick=()=>enter(false);$('start').onclick=()=>reset(Math.max(0,Math.min(levelCount-1,Number(net.room.selectedLevel)||0)));$('roomStage').onchange=()=>{if(net?.host&&net.room?.status==='lobby')net.ref.update({selectedLevel:selectedLevel($('roomStage'))}).catch(e=>message(e.message))};$('helpButton').onclick=()=>{$('help').style.display=$('help').style.display==='block'?'none':'block'};
async function leave(){audio()?.stopMusic();keys={};state=null;target=null;paused=false;if(net)await net.leave();net=null;local=true;$('game').style.display='none';$('overlay').style.display='none';$('lobby').hidden=true;$('title').hidden=false;recommendStage();$('local').focus()}
$('leave').onclick=leave;$('exit').onclick=leave;$('menu').onclick=()=>{paused=!paused;overlay()};$('mute').onclick=()=>{muted=!muted;audio()?.setMuted(muted);$('mute').textContent=muted?'♩':'♪'};
$('continue').onclick=()=>{if(!state)return;if(paused){paused=false;overlay();return}if(!local&&!net.host)return;if(state.status==='clear'&&state.level===levelCount-1){leave();return}reset(state.status==='clear'?state.level+1:state.level);sound('retry')};
function input(first=true){if(paused||state?.status!=='play')return {left:false,right:false,jump:false};return first?{left:!!keys.ArrowLeft,right:!!keys.ArrowRight,jump:!!keys.ArrowUp}:{left:!!keys.KeyA,right:!!keys.KeyD,jump:!!keys.KeyW}}
addEventListener('keydown',e=>{if(['INPUT','SELECT','TEXTAREA'].includes(document.activeElement.tagName))return;audio()?.unlock();if(e.code==='KeyF'){document.fullscreenElement?document.exitFullscreen():document.documentElement.requestFullscreen();return}if(!state){if(['INPUT','SELECT','TEXTAREA'].includes(document.activeElement.tagName))return;if(['ArrowDown','ArrowUp'].includes(e.code)&&document.activeElement.tagName!=='INPUT'){e.preventDefault();const panel=$('title').hidden?$('lobby'):$('title'),buttons=[...panel.querySelectorAll('button,select,input')].filter(b=>!b.disabled);let i=buttons.indexOf(document.activeElement);buttons[(i+(e.code==='ArrowDown'?1:-1)+buttons.length)%buttons.length]?.focus();}return;}if(['ArrowLeft','ArrowRight','ArrowUp','KeyW','KeyA','KeyD','Space'].includes(e.code)){e.preventDefault();keys[e.code]=true}if(e.repeat)return;if(e.code==='KeyR'&&(local||net.host)){reset(state.level);sound('retry')}if(e.code==='Escape'){paused=!paused;overlay()}});addEventListener('keyup',e=>keys[e.code]=false);addEventListener('blur',()=>{keys={}});document.addEventListener('visibilitychange',()=>{keys={};if(document.hidden)audio()?.stopMusic();else if(state)audio()?.startMusic()});
function failureText(){if(!state?.failure)return '';const i=state.players.findIndex(p=>p.id===state.failure.playerId);return (i>=0?String(i+1)+'번 · ':'')+(state.failure.reason==='fall'?'아래로 떨어졌어요':'가시에 닿았어요');}
function overlay(){const end=state&&state.status!=='play';$('overlay').style.display=paused||end?'grid':'none';$('result').textContent=paused?'잠깐 쉬어요':state?.status==='clear'?(state.level===levelCount-1?'모두 함께 성공!':'함께 성공!'):'다시 함께!';$('reason').textContent=paused?'':state?.status==='dead'?failureText():'';$('continue').textContent=paused?'계속':state?.status==='clear'?(state.level===levelCount-1?'끝내기':'다음 구역'):'다시 도전';$('continue').disabled=!local&&!net?.host&&!paused;if(paused||end)$('continue').focus()}
function events(before,current=state){if(!before)return;if(!before.keyTaken&&current.keyTaken)sound('key');if(!before.gateOpen&&current.gateOpen)sound('switch');for(let i=0;i<current.players.length;i++){const a=before.players[i],b=current.players[i];if(a&&a.vy>=0&&b.vy<0)sound('jump');if(a&&!a.ground&&b.ground)sound('land')}if(current.status!==lastStatus){lastStatus=current.status;if(current.status==='clear'){highestClear=Math.max(highestClear,current.level);try{localStorage.setItem(progressKey,String(highestClear))}catch{}}if(current.status!=='play')sound(current.status==='clear'?'clear':'death');overlay()}}
function draw(){if(!state)return;const m=state.map;ctx.fillStyle='#0a2330';ctx.fillRect(0,0,1200,675);ctx.fillStyle='#173c4a';for(let i=0;i<12;i++){ctx.beginPath();ctx.arc(i*130+20,640,120+(i%3)*30,0,Math.PI*2);ctx.fill()}ctx.fillStyle='#294f5b';for(const p of m.platforms){ctx.fillRect(p.x,p.y,p.w,p.h);ctx.fillStyle='#62a394';ctx.fillRect(p.x,p.y,p.w,6);ctx.fillStyle='#294f5b'}for(const h of m.hazards){ctx.fillStyle='#ff6a7e';if(h.shape&&h.shape!=='spike'){ctx.fillRect(h.x,h.y,h.w,h.h);}else for(const t of ParkHazards.triangles(h)){ctx.beginPath();ctx.moveTo(t[0].x,t[0].y);ctx.lineTo(t[1].x,t[1].y);ctx.lineTo(t[2].x,t[2].y);ctx.closePath();ctx.fill()}}
 ctx.fillStyle=state.keyTaken&&state.gateOpen?'#a5f0a1':'#456575';ctx.fillRect(m.exit.x,m.exit.y,m.exit.w,m.exit.h);ctx.fillStyle='#163941';ctx.fillRect(m.exit.x+8,m.exit.y+8,m.exit.w-16,m.exit.h-8);ctx.fillStyle='#a5f0a1';ctx.strokeStyle='#a5f0a1';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(m.exit.x+29,m.exit.y+47);ctx.lineTo(m.exit.x+29,m.exit.y+24);ctx.moveTo(m.exit.x+20,m.exit.y+33);ctx.lineTo(m.exit.x+29,m.exit.y+24);ctx.lineTo(m.exit.x+38,m.exit.y+33);ctx.stroke();
 if(m.gate&&!state.gateOpen){ctx.fillStyle='#dd91a6';ctx.fillRect(m.gate.x,m.gate.y,m.gate.w,m.gate.h)}for(let si=0;si<m.switches.length;si++){const sw=m.switches[si],active=!!state.switchActive?.[si];ctx.fillStyle=active?'#9bea9a':state.gateOpen?'#638e7c':'#ffd377';ctx.fillRect(sw.x,sw.y,sw.w,sw.h);if(sw.accept==='crate'){ctx.strokeStyle=active?'#9bea9a':'#c98f55';ctx.lineWidth=2;ctx.strokeRect(sw.x+sw.w/2-9,sw.y-35,18,18);ctx.beginPath();ctx.moveTo(sw.x+sw.w/2-6,sw.y-32);ctx.lineTo(sw.x+sw.w/2+6,sw.y-20);ctx.stroke()}const holders=sw.accept==='crate'?[]:state.players.map((p,i)=>({p,i})).filter(({p})=>E.overlap({...p,y:p.y+3},sw));holders.forEach(({i},di)=>{ctx.fillStyle=colors[i%8];ctx.beginPath();ctx.arc(sw.x+sw.w/2+(di-(holders.length-1)/2)*12,sw.y-10,4,0,Math.PI*2);ctx.fill()});if(active&&!holders.length){ctx.fillStyle='#c98f55';ctx.fillRect(sw.x+sw.w/2-4,sw.y-14,8,8)}}for(const c of m.crates){ctx.fillStyle='#c98f55';ctx.fillRect(c.x,c.y,c.w,c.h);ctx.strokeStyle='#775230';ctx.lineWidth=4;ctx.strokeRect(c.x+5,c.y+5,c.w-10,c.h-10);ctx.beginPath();ctx.moveTo(c.x+5,c.y+5);ctx.lineTo(c.x+c.w-5,c.y+c.h-5);ctx.stroke()}
 if(!state.keyTaken){ctx.fillStyle='#ffd15c';ctx.strokeStyle='#ffd15c';ctx.lineWidth=4;ctx.beginPath();ctx.arc(m.key.x+7,m.key.y+7,6,0,Math.PI*2);ctx.moveTo(m.key.x+7,m.key.y+13);ctx.lineTo(m.key.x+7,m.key.y+25);ctx.lineTo(m.key.x+14,m.key.y+25);ctx.moveTo(m.key.x+7,m.key.y+20);ctx.lineTo(m.key.x+12,m.key.y+20);ctx.stroke()}state.players.forEach((p,i)=>{if(p.exit)return;ctx.save();ctx.translate(p.x,p.y);ctx.fillStyle=colors[i%8];ctx.beginPath();ctx.roundRect(0,0,p.w,p.h,10);ctx.fill();ctx.beginPath();ctx.moveTo(0,20);ctx.lineTo(-9,12);ctx.lineTo(-9,28);ctx.fill();ctx.fillStyle='#092733';ctx.fillRect(10,12,4,5);ctx.fillRect(23,12,4,5);ctx.fillStyle='white';ctx.font='12px system-ui';ctx.textAlign='center';ctx.fillText(!local&&p.id===net?.id?'나 · '+(i+1):String(i+1),16,-9);if(state.level===0&&state.ticks<600&&(local||p.id===net?.id)){ctx.font='bold 13px system-ui';ctx.fillText(local&&i===1?'A D · W':'← → · ↑',16,-43)}if(p.key){ctx.fillStyle='#ffd15c';ctx.fillRect(10,-29,12,4);ctx.fillRect(10,-35,3,9);ctx.fillRect(15,-37,3,9);ctx.fillRect(20,-35,3,9)}ctx.restore()});$('stage').textContent=`${String(state.level+1).padStart(2,'0')} / ${levelCount} · ${m.name}`;$('progress').textContent=`${state.keyTaken?'🔑 ✓':'🔑 ○'}${m.switches.length?'  ⏚ '+(state.switchActive||[]).filter(Boolean).length+'/'+m.switches.length+(state.gateOpen?' ✓':''):''}  ⚑ ${state.players.filter(p=>p.exit).length}/${state.players.length}`;$('progress').setAttribute('aria-label',`열쇠 ${state.keyTaken?'획득':'미획득'}, 스위치 ${(state.switchActive||[]).filter(Boolean).length}/${m.switches.length}, 도착 ${state.players.filter(p=>p.exit).length}/${state.players.length}`);}
function loop(now){const dt=Math.min(.05,(now-last)/1000);last=now;if(state){acc+=dt;if(local||net?.host){let before=JSON.parse(JSON.stringify(state));while(acc>=1/60){if(!paused||!local){const inputs=local?{local1:input(),local2:input(false)}:{...net.inputs,[net.id]:input()};for(const [id,v]of Object.entries(inputs))if(v.at&&Date.now()-v.at>800)inputs[id]={};E.step(state,inputs)}acc-=1/60}events(before);if(!local&&(publish+=dt)>.083){publish=0;net.publish(state)}}else{acc=0;if(target){state.map=target.map;for(const p of state.players){const t=target.players.find(x=>x.id===p.id);if(t){p.x+=(t.x-p.x)*Math.min(1,dt*16);p.y+=(t.y-p.y)*Math.min(1,dt*16);p.key=t.key;p.exit=t.exit}}state.keyTaken=target.keyTaken;state.gateOpen=target.gateOpen;state.switchActive=target.switchActive||[];state.failure=target.failure;state.ticks=target.ticks;events(null)}}if(!local){const v=input(),text=JSON.stringify(v);if(text!==lastSent||now-(loop.sent||0)>250){lastSent=text;loop.sent=now;net.input(v)}}draw()}requestAnimationFrame(loop)}requestAnimationFrame(loop);
document.getElementById('local').focus();
$('mute').addEventListener('click',()=>{
  $('mute').setAttribute('aria-label',muted?'소리 켜기':'소리 끄기');
  $('mute').setAttribute('aria-pressed',String(muted));
});
})();
