/* Host owns physics; peers publish sequenced inputs, receive 12 Hz state snapshots. */
window.CoopNetwork=class{
 constructor(onRoom,onError){this.onRoom=onRoom;this.onError=onError;this.id='p'+Math.random().toString(36).slice(2,12);this.seq=0;this.jumpSeq=0;this.lastJump=false;this.inputs={};this.clean=[];}
 init(){if(this.db)return; if(!window.firebase)throw Error('온라인 연결을 불러오지 못했어요');if(!firebase.apps.length)firebase.initializeApp({apiKey:'AIzaSyD8_pSiOVOWmCitHl_nWcgSZobMFI5NgXM',authDomain:'rolling2-17a8f.firebaseapp.com',databaseURL:'https://rolling2-17a8f-default-rtdb.asia-southeast1.firebasedatabase.app',projectId:'rolling2-17a8f'});this.db=firebase.database();}
 async enter(code,create=false){this.init();this.code=code;this.ref=this.db.ref('games/coop_'+code);const warm=()=>{};this.ref.on('value',warm);await this.ref.once('value');const result=await this.ref.transaction(v=>{if(create){if(v)return;v={host:this.id,status:'lobby',created:Date.now()};}if(!v||v.status!=='lobby'||Object.keys(v.players||{}).length>=8)return;v.players=v.players||{};v.players[this.id]={name:'참치 '+this.id.slice(-3),joined:Date.now()};return v;});this.ref.off('value',warm);if(!result.committed){this.ref=null;throw Error('참가할 수 없어요. 방 코드·인원·진행 상태를 확인해주세요');}
 this.player=this.ref.child('players/'+this.id);this.player.onDisconnect().remove();this.ref.child('inputs/'+this.id).onDisconnect().remove();this.ref.on('value',snap=>{const r=snap.val();if(!r){this.onError('방이 닫혔어요');return;}const wasHost=this.host;this.room=r;this.host=r.host===this.id;this.justBecameHost=this.host&&!wasHost;this.inputs=r.inputs||{};this.onRoom(r);if(!r.players||!r.players[r.host]){const next=Object.keys(r.players||{}).sort()[0];if(next===this.id)this.ref.child('host').transaction(h=>h===r.host?this.id:undefined).catch(e=>this.onError(e.message));}},e=>this.onError(e.message));}
 input(input){if(!this.ref)return;if(input.jump&&!this.lastJump)this.jumpSeq++;this.lastJump=input.jump;this.ref.child('inputs/'+this.id).set({...input,jumpSeq:this.jumpSeq,seq:++this.seq,at:Date.now()}).catch(e=>this.onError(e.message));}
 publish(state){if(this.host&&this.ref)this.ref.update({state,status:state.status==='play'?'game':state.status}).catch(e=>this.onError(e.message));}
 start(state){if(this.host)return this.ref.update({state,status:'game'}).catch(e=>this.onError(e.message));}
 async leave(){if(this.ref){this.ref.off();const warm=()=>{};this.ref.on('value',warm);await this.player.remove();await this.ref.child('inputs/'+this.id).remove();await this.ref.once('value');await this.ref.transaction(room=>room&&Object.keys(room.players||{}).length===0?null:undefined);this.ref.off('value',warm);}this.ref=null;this.room=null;}
};
