'use strict';
(() => {
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const MODES=[{id:'world',title:'모험',line:'어깨를 빌려, 함께 앞으로',colors:['#326e69','#1e494c'],symbol:'bridge'},{id:'dark',title:'한계 도전',line:'조금 더 대담한 우리',colors:['#565380','#333755'],symbol:'stars'},{id:'battle',title:'대전',line:'이번에는 누가 이길까?',colors:['#a36852','#624e51'],symbol:'versus'},{id:'endless',title:'무한 도전',line:'우리의 기록은 어디까지?',colors:['#466d94','#29455e'],symbol:'infinity'}];
let playerCount=Math.max(2,Math.min(8,Number(sessionStorage.getItem('park-player-count'))||2));
let data,screen='title',titleIndex=0,modeIndex=0,settingIndex=0,selection={mode:'world',game:'pico1',chapter:0,card:0},stageEntries=[],chapterList=[],toastTimer,helpReturn;
const systemMotion=matchMedia('(prefers-reduced-motion: reduce)').matches;
let reduced=systemMotion;
try{const saved=JSON.parse(sessionStorage.getItem('park-menu-selection')||'null');if(saved&&MODES.some(m=>m.id===saved.mode)&&['pico1','pico2'].includes(saved.game))selection={mode:saved.mode,game:saved.game,chapter:Math.max(0,Number(saved.chapter)||0),card:Math.max(0,Number(saved.card)||0)};const value=localStorage.getItem('park-reduced-motion');if(value!==null)reduced=value==='true';}catch{}
document.body.classList.toggle('reduce-motion',reduced);
const focus=e=>e?.focus({preventScroll:true});
function store(){try{sessionStorage.setItem('park-menu-selection',JSON.stringify(selection));}catch{}}
function notify(message){clearTimeout(toastTimer);$('toast').textContent=message;$('toast').hidden=false;toastTimer=setTimeout(()=>$('toast').hidden=true,2600);}
function artwork(type){const fish=(x,y,color,size=65)=>`<use href="#fish" x="${x}" y="${y}" width="${size}" height="${size*.9}" style="color:${color}"/>`;
 let scene='';if(type==='bridge')scene=`<path d="M15 165h100m70-45h95" stroke="#93cdb0" stroke-width="18" stroke-linecap="round"/><path d="M110 164q42 17 82-37" stroke="#b1cdad" stroke-width="3" stroke-dasharray="8 6" fill="none"/>${fish(42,108,'#75e3c1')}${fish(200,62,'#ffc38b')}<path d="m162 41 5 13 14 1-11 9 4 14-12-8-12 8 4-14-11-9 14-1z" fill="#ffe5a8"/>`;
 if(type==='stars')scene=`<path d="M10 175h75m30-37h70m35-37h75" stroke="#9592b6" stroke-width="14" stroke-linecap="round"/>${fish(105,81,'#b8b0ef')}<path d="m216 30 9 18 19 3-14 14 3 20-17-9-17 9 3-20-14-14 20-3z" fill="#ebdcb2"/>`;
 if(type==='versus')scene=`<path d="M25 174h250" stroke="#e5b290" stroke-width="15" stroke-linecap="round"/>${fish(30,102,'#7ce3c1',80)}${fish(190,102,'#ffbc8b',80)}<path d="m151 64-15 33 18-3-7 34 23-45-18 6z" fill="#ffe4a0"/>`;
 if(type==='infinity')scene=`<path d="M26 166h75m37-17h68m23 27h56" stroke="#9abbcc" stroke-width="13" stroke-linecap="round"/><path d="M91 69c-25-37-56-27-56-4s25 31 47 6l20-20c24-25 56-17 56 6s-30 33-57-3" transform="translate(54 0)" fill="none" stroke="#c4e5d1" stroke-width="7" stroke-linecap="round"/>${fish(148,97,'#88e1d1',58)}`;
 return `<svg viewBox="0 0 300 210" aria-hidden="true"><circle cx="235" cy="46" r="90" fill="#ffffff08"/><circle cx="54" cy="51" r="3" fill="#fff7"/><circle cx="260" cy="105" r="2" fill="#fff7"/>${scene}</svg>`;
}
function descriptor(id){return (typeof globalThis.ParkDemoStages?.list==='function'?ParkDemoStages.list():globalThis.ParkDemoStages?.list||[]).find(d=>d.id===id);}
function mapArtwork(id){try{const m=ParkDemoStages.createStage(id,playerCount);if(!m)return '';const rect=(p,color)=>'<rect x="'+p.x+'" y="'+p.y+'" width="'+p.w+'" height="'+p.h+'" fill="'+color+'" rx="3"/>';return '<svg class="map-preview" viewBox="0 0 '+m.width+' '+(m.height||720)+'" preserveAspectRatio="xMidYMid meet" aria-label="스테이지 구조 미리보기"><rect width="100%" height="100%" fill="#112d3b"/>'+(m.platforms||[]).map(p=>rect(p,'#639791')).join('')+(m.devices||[]).map(p=>rect(p,p.kind==='lift'?'#f9c77c':'#70d4b9')).join('')+(m.movingPlatforms||[]).map(p=>rect(p,'#91b9e7')).join('')+(m.crates||[]).map(p=>rect(p,'#c89761')).join('')+(m.springs||[]).map(p=>rect(p,'#b99cea')).join('')+(m.coins||[]).map(p=>'<circle cx="'+(p.x+(p.w||18)/2)+'" cy="'+(p.y+(p.h||18)/2)+'" r="10" fill="#ffdb70"/>').join('')+(m.hazards||[]).map(p=>rect(p,'#e67589')).join('')+(m.spawns||[]).map(p=>rect({...p,w:32,h:38},'#c0eadc')).join('')+(m.exit?rect(m.exit,'#e3d596'):'')+'</svg>';}catch{return '';}}
function miniArtwork(id){try{const s=ParkMiniGames.create(id,playerCount),palette=['#76e4c2','#ffbe86','#b6a1ed','#ee8dad','#abd983','#83c8ea','#efd277','#f0f1df'];const rect=(x,y,w,h,c)=>'<rect x="'+x+'" y="'+y+'" width="'+w+'" height="'+h+'" rx="5" fill="'+c+'"/>';const circle=(x,y,r,c)=>'<circle cx="'+x+'" cy="'+y+'" r="'+r+'" fill="'+c+'"/>';let scene='';for(const [i,p] of s.players.entries())scene+=rect(p.x,p.y,35,38,palette[i]);if(s.grid)s.grid.forEach((row,y)=>row.forEach((v,x)=>{if(v)scene+=rect(150+x*900/s.cols,50+y*40,900/s.cols-3,37,palette[(v-1)%8]);}));if(s.pieces)s.pieces.forEach((p,i)=>{scene+=rect(150+p.x*900/s.cols,50+p.y*40,900/s.cols-3,77,palette[i]);});for(const b of s.bricks||[])scene+=rect(b.x,b.y,b.w,b.h,'#d7b880');if(s.ball)scene+=circle(s.ball.x,s.ball.y,12,'#fff8cb');if(s.hoop)scene+='<path d="M'+s.hoop.x+' '+s.hoop.y+'h100v50h-100z" fill="none" stroke="#eaa083" stroke-width="8"/>';for(const p of s.platforms||[])scene+=rect(p.x,p.y,p.w,p.h,'#73a999');if(['precision','reaction'].includes(s.family))scene+=circle(600,245,100,s.family==='reaction'?'#edac86':'#a9dcd4')+'<text x="600" y="270" text-anchor="middle" fill="#183b43" font-size="70" font-family="system-ui">'+(s.limit||'●')+'</text>';if(s.pattern)s.pattern.forEach((v,i)=>scene+=rect(120+i*960/s.count,170+v*24,60,60,palette[i]));if(s.family==='graph')scene+=rect(250,200,s.targetLeft*65,110,'#79ddc0')+rect(720,200,s.targetRight*65,110,'#f2bb81');if(s.family==='whack')scene+=circle(600,300,70,'#f5be84');return '<svg class="map-preview" viewBox="0 0 1200 675" aria-label="미니게임 초기 구조 미리보기"><rect width="1200" height="675" fill="#112d3b"/>'+scene+'</svg>';}catch{return '';}}
function changeCount(n){playerCount=Math.max(2,Math.min(8,playerCount+n));sessionStorage.setItem('park-player-count',String(playerCount));$('party-count').textContent=playerCount+'인';if(screen==='stages')renderStages(false);}
function mode(){return MODES[modeIndex];}
function updateHints(){let items=[];if(screen==='title'||screen==='settings')items=[['↑ ↓','이동'],['Enter','선택']];if(screen==='lobby')items=[['← →','이동'],['Enter','선택']];if(screen==='stages')items=[['← →','카드'],['↑ ↓','챕터'],['Q E','모험'],['Enter','시작']];if(screen!=='title')items.push(['⌫','뒤로']);else items.push(['F','전체화면']);$('hints').innerHTML=items.map(([key,label])=>label==='뒤로'?`<button class="back-button" id="footer-back" title="뒤로 · Backspace 또는 Esc"><kbd>${key}</kbd> ${label}</button>`:`<span><kbd>${key}</kbd>${label}</span>`).join('');$('footer-back')?.addEventListener('click',back);$('route-name').textContent={title:'함께 가는 모험',lobby:'모험 고르기',stages:'스테이지 고르기',settings:'나에게 맞게'}[screen];}
function show(next,{focusMenu=true,writeHash=true}={}){screen=next;for(const name of ['title','lobby','stage','settings'])$(name+'-screen').hidden=name!==(next==='stages'?'stage':next);if(writeHash)history.replaceState(null,'',next==='title'?location.pathname:'#'+next);if(next==='title')selectTitle(titleIndex,focusMenu);if(next==='lobby'){renderModes();selectMode(modeIndex,focusMenu);}if(next==='stages')renderStages(focusMenu);if(next==='settings')renderSettings(focusMenu);updateHints();$('toast').hidden=true;}
function selectTitle(i,doFocus=true){titleIndex=(i+2)%2;document.querySelectorAll('[data-title]').forEach((b,n)=>{b.classList.toggle('selected',n===titleIndex);if(n===titleIndex&&doFocus)focus(b);});}
function renderModes(){$('modes').innerHTML=MODES.map((m,i)=>`<button class="mode-card ${i===modeIndex?'selected':''}" data-mode="${i}"><div class="mode-picture" style="--scene-a:${m.colors[0]};--scene-b:${m.colors[1]}"><span class="mode-number">0${i+1}</span>${artwork(m.symbol)}</div><div class="mode-copy"><h2>${m.title}</h2><p>${m.line}</p><span>${data.entries.some(e=>e.mode===m.id&&e.playable)?'데모 플레이':'준비 중'}</span><strong aria-hidden="true">↗</strong></div></button>`).join('');document.querySelectorAll('[data-mode]').forEach(b=>{const i=Number(b.dataset.mode);b.addEventListener('focus',()=>selectMode(i,false));b.addEventListener('click',()=>{selectMode(i,false);openMode();});});}
function selectMode(i,doFocus=true){modeIndex=(i+MODES.length)%MODES.length;document.querySelectorAll('[data-mode]').forEach((b,n)=>{b.classList.toggle('selected',n===modeIndex);if(n===modeIndex&&doFocus)focus(b);});}
function openMode(){if(selection.mode!==mode().id)selection={mode:mode().id,game:selection.game,chapter:0,card:0};show('stages');}
function chapters(){let list=data.chapters.filter(c=>c.mode===selection.mode&&c.game===selection.game);if(!list.length){selection.game=selection.game==='pico1'?'pico2':'pico1';list=data.chapters.filter(c=>c.mode===selection.mode&&c.game===selection.game);}return list;}
function renderStages(doFocus=true){chapterList=chapters();selection.chapter=Math.min(selection.chapter,chapterList.length-1);selection.card=Math.max(0,selection.card);const chapter=chapterList[selection.chapter];if(!chapter){notify('아직 준비 중인 모험이에요.');show('lobby');return;}
 stageEntries=chapter.sourceIds.map(id=>data.entries.find(e=>e.id===id));for(const e of stageEntries)if(e.playable)e.demoPreview=e.mini?miniArtwork(e.id):mapArtwork(e.id);selection.card=Math.min(selection.card,stageEntries.length-1);const chosenMode=MODES.find(m=>m.id===selection.mode);$('stage-mode').textContent=chosenMode.title;$('stage-path').textContent='참치파크 · 기믹 데모 (원작 배치 아님)';$('chapter-name').innerHTML=`${esc(chapter.title)} <small>${selection.chapter+1} / ${chapterList.length}</small>`;$('chapter-prev').disabled=selection.chapter===0;$('chapter-next').disabled=selection.chapter===chapterList.length-1;
 document.querySelectorAll('[data-game]').forEach(b=>{const available=data.chapters.some(c=>c.mode===selection.mode&&c.game===b.dataset.game);b.hidden=!available;b.classList.toggle('active',b.dataset.game===selection.game);b.setAttribute('aria-pressed',String(b.dataset.game===selection.game));});
 $('cards').innerHTML=stageEntries.map((e,i)=>`<button class="stage-card ${i===selection.card?'selected':''}" data-card="${i}" aria-label="${esc(e.title)}, ${esc(e.mechanic)}, ${e.playable?'데모':'준비 중'}"><div class="card-image">${e.demoPreview?e.demoPreview:e.preview?`<img src="${e.preview}" alt="${esc(e.title)} 실제 게임 미리보기" draggable="false">`:`${artwork(chosenMode.symbol)}<div class="placeholder-label"><svg style="width:26px;height:28px;opacity:1;margin:auto" viewBox="0 0 32 32" aria-hidden="true"><use href="#${e.playable?'fish':'lock'}"/></svg><span>${e.playable?'미니게임':'미리보기 준비 중'}</span></div>`}<span class="image-badge ${e.playable?'ready':''}">${e.playable?'기믹 데모':'준비 중'}</span></div><div class="card-copy"><h2>${esc(e.title)}</h2><p>${esc(e.mechanic)}</p></div></button>`).join('');
 document.querySelectorAll('[data-card]').forEach(b=>{const i=Number(b.dataset.card);b.addEventListener('focus',()=>selectCard(i,false));b.addEventListener('click',()=>selectCard(i));b.addEventListener('dblclick',launch);});selectCard(selection.card,doFocus,false);store();}
function selectCard(i,doFocus=true,smooth=true){if(!stageEntries.length)return;selection.card=Math.max(0,Math.min(stageEntries.length-1,i));const buttons=[...document.querySelectorAll('[data-card]')];buttons.forEach((b,n)=>{b.classList.toggle('selected',n===selection.card);b.setAttribute('aria-current',n===selection.card?'true':'false');});const target=buttons[selection.card];if(doFocus)focus(target);requestAnimationFrame(()=>{const rail=$('cards');const inset=Math.max(0,(rail.clientWidth-target.offsetWidth)/2);rail.style.paddingLeft=inset+'px';rail.style.paddingRight=inset+'px';const left=target.offsetLeft-inset;rail.scrollTo({left,behavior:smooth&&!reduced?'smooth':'instant'});});const e=stageEntries[selection.card];$('launch').textContent=e.playable?'함께 시작  →':'제작 중';$('launch').setAttribute('aria-disabled',String(!e.playable));$('stage-caption').textContent=e.playable?'기믹만 재현한 데모예요 · 원작 지형이 아닙니다 · 로컬 '+playerCount+'인':'아직 준비 중인 스테이지예요';$('party-count').textContent=playerCount+'인';$('dots').innerHTML=stageEntries.map((_,n)=>`<i class="${n===selection.card?'on':''}"></i>`).join('');store();}
function changeChapter(delta){const next=Math.max(0,Math.min(chapterList.length-1,selection.chapter+delta));if(next===selection.chapter)return;selection.chapter=next;selection.card=0;renderStages();}
function changeGame(game){if(!data.chapters.some(c=>c.mode===selection.mode&&c.game===game))return;selection.game=game;selection.chapter=0;selection.card=0;renderStages();}
function launch(){const e=stageEntries[selection.card];if(!e?.playable){notify('이 스테이지는 아직 준비 중이에요.');return;}store();location.assign('../rebuild/'+(e.mini?'mini.html':'index.html')+'?from=menu&id='+encodeURIComponent(e.id)+'&count='+playerCount);}
function back(){if($('help-dialog').open){closeHelp();return;}if(screen==='stages'){modeIndex=MODES.findIndex(m=>m.id===selection.mode);show('lobby');}else if(screen==='lobby'||screen==='settings')show('title');}
function renderSettings(doFocus=true){$('full-value').textContent=document.fullscreenElement?'켜짐':'꺼짐';$('motion-value').textContent=reduced?'줄임':'켜짐';document.querySelectorAll('[data-setting]').forEach((b,i)=>{b.classList.toggle('selected',i===settingIndex);if(i===settingIndex&&doFocus)focus(b);});}
async function toggleFullscreen(){try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen();}catch{notify('브라우저에서 전체화면을 사용할 수 없어요.');}renderSettings(false);}
function settingAction(){if(settingIndex===0)toggleFullscreen();else if(settingIndex===1){reduced=!reduced;document.body.classList.toggle('reduce-motion',reduced);try{localStorage.setItem('park-reduced-motion',String(reduced));}catch{}renderSettings();}else if(settingIndex===2)openHelp();else location.assign('status.html');}
function openHelp(){const entry=screen==='stages'?stageEntries[selection.card]:null;$('stage-help').hidden=!entry;if(entry){$('stage-help').innerHTML='<h3>'+esc(entry.title)+'</h3><p>원작 규칙: '+esc(entry.originalMechanic||entry.mechanic)+'</p>'+(entry.omittedRules?.length?'<p>구현 대기: '+esc(entry.omittedRules.join(' · '))+'</p>':'')+'<p>데모의 배치와 수치는 검수 중입니다.</p>';}helpReturn=document.activeElement;if(!$('help-dialog').open)$('help-dialog').showModal();focus($('close-help'));}
function closeHelp(){$('help-dialog').close();focus(helpReturn);}
document.querySelectorAll('[data-title]').forEach(b=>{b.addEventListener('focus',()=>selectTitle(Number(b.dataset.title),false));b.addEventListener('click',()=>show(Number(b.dataset.title)===0?'lobby':'settings'));});
document.querySelectorAll('[data-setting]').forEach(b=>{b.addEventListener('focus',()=>{settingIndex=Number(b.dataset.setting);renderSettings(false);});b.addEventListener('click',()=>{settingIndex=Number(b.dataset.setting);settingAction();});});
document.querySelectorAll('[data-game]').forEach(b=>b.addEventListener('click',()=>changeGame(b.dataset.game)));
$('party-minus').onclick=()=>changeCount(-1);$('party-plus').onclick=()=>changeCount(1);
$('home').onclick=()=>show('title');$('help').onclick=openHelp;$('close-help').onclick=closeHelp;$('help-dialog').addEventListener('cancel',e=>{e.preventDefault();closeHelp();});$('fullscreen').onclick=toggleFullscreen;$('launch').onclick=launch;$('chapter-prev').onclick=()=>changeChapter(-1);$('chapter-next').onclick=()=>changeChapter(1);
document.addEventListener('fullscreenchange',()=>{renderSettings(false);$('fullscreen').setAttribute('aria-label',document.fullscreenElement?'전체화면 해제':'전체화면');});
addEventListener('resize',()=>{if(screen==='stages')selectCard(selection.card,false,false);});
addEventListener('hashchange',()=>{const requested=location.hash.slice(1);if(['title','lobby','stages','settings'].includes(requested))show(requested,{writeHash:false});else show('title',{writeHash:false});});
addEventListener('keydown',e=>{
 if(!data||e.altKey||e.ctrlKey||e.metaKey)return;
 if($('help-dialog').open){if(['Escape','Backspace'].includes(e.key)){e.preventDefault();closeHelp();}return;}
 if(e.code==='KeyF'){e.preventDefault();if(!e.repeat)toggleFullscreen();return;}if(e.code==='KeyH'){e.preventDefault();if(!e.repeat)openHelp();return;}
 if(['Escape','Backspace'].includes(e.key)){e.preventDefault();if(!e.repeat)back();return;}
 if(screen==='stages'&&['BracketLeft','BracketRight'].includes(e.code)){e.preventDefault();changeCount(e.code==='BracketLeft'?-1:1);return;}
 if(e.key==='Enter'){if(e.repeat){e.preventDefault();return;}const a=document.activeElement;if(a?.closest('.topbar')||a?.matches('[data-game],#chapter-prev,#chapter-next,#footer-back,#party-minus,#party-plus'))return;e.preventDefault();if(screen==='title')show(titleIndex===0?'lobby':'settings');else if(screen==='lobby')openMode();else if(screen==='stages')launch();else settingAction();return;}
 if(!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','KeyQ','KeyE'].includes(e.code))return;e.preventDefault();
 if(screen==='title'){if(e.code==='ArrowUp'||e.code==='ArrowDown')selectTitle(titleIndex+(e.code==='ArrowUp'?-1:1));}
 else if(screen==='settings'){if(e.code==='ArrowUp'||e.code==='ArrowDown'){settingIndex=(settingIndex+(e.code==='ArrowUp'?-1:1)+4)%4;renderSettings();}}
 else if(screen==='lobby'){const vertical=matchMedia('(max-width:560px)').matches?2:1;const delta={ArrowLeft:-1,ArrowRight:1,ArrowUp:-vertical,ArrowDown:vertical}[e.code];if(delta)selectMode(modeIndex+delta);}
 else if(screen==='stages'){if(e.code==='ArrowLeft'||e.code==='ArrowRight')selectCard(selection.card+(e.code==='ArrowLeft'?-1:1));if(e.code==='ArrowUp'||e.code==='ArrowDown')changeChapter(e.code==='ArrowUp'?-1:1);if(e.code==='KeyQ'||e.code==='KeyE')changeGame(e.code==='KeyQ'?'pico1':'pico2');}
});
fetch('menu-data.json').then(r=>{if(!r.ok)throw Error('menu load failed');return r.json();}).then(result=>{data=result;for(const e of data.entries){const d=descriptor(e.id);e.mini=!!globalThis.ParkMiniGames?.supports(e.id);e.playable=(!!d?.playable&&d.route!=='mini')||e.mini;e.originalMechanic=e.mechanic;e.omittedRules=d?.omittedRules||[];if(e.playable)e.mechanic=d?.implementedRules?.length?d.implementedRules.join(' · '):(e.mini?ParkMiniGames.descriptor(e.id)?.title:'협동 데모');e.demoPreview=e.playable?(e.mini?miniArtwork(e.id):mapArtwork(e.id)):'';if(!e.playable)e.preview=null;}modeIndex=Math.max(0,MODES.findIndex(m=>m.id===selection.mode));$('loading').hidden=true;const hash=location.hash.slice(1);show(['lobby','stages','settings'].includes(hash)?hash:'title',{writeHash:false});}).catch(()=>{$('loading').innerHTML='<span>잠시만요</span><p>메뉴를 불러오지 못했어요.</p><button class="launch" id="retry-load">다시 불러오기</button>';$('retry-load').onclick=()=>location.reload();});
})();
